/* STUDENTS:  DO NOT EDIT THIS FILE.  INSTEAD, CREATE YOUR OWN UNIT TESTS ACCORDING
TO THE LAB DOCUMENT.
*/

// Google Test Framework
#include <gtest/gtest.h>
// Project code from the ../src directory
#include "../src/Duck.h"
//#include <iostream>
#include <string.h>

#ifdef FEEDBACK_TEST_01
// Initial Test for Rubber Duck.  YayYay

TEST(RubberDuckTest,Constructor){
  RubberDuck my_ralph;
  string except_str1_1 = "Cannot fly.";
  EXPECT_EQ(except_str1_1,my_ralph.performFly()) << "FAIL: performFly" ;

  string except_str1_2 = "Quack at 2 decibels.";
  EXPECT_EQ(except_str1_2,my_ralph.performQuack()) << "FAIL: performQuack" ;

  Quack q;
  my_ralph.setQuackBehavior(&q);
  string except_str1_3 = "Quack at 10 decibels.";
  EXPECT_EQ(except_str1_3,my_ralph.performQuack()) << "FAIL: performQuack of setQuackBehavior" ;

  FlyWithWings f;
  my_ralph.setFlyBehavior(&f);
  string except_str1_4 = "Fly with wings at speed of 5 mph.";
  EXPECT_EQ(except_str1_4,my_ralph.performFly()) << "FAIL: performFly of setFlyBehavior" ;
}

TEST(RubberDuckTest,display){
  RubberDuck my_ralph1;
  string except_str1_5="I am a Rubber Duck.";
  EXPECT_EQ(except_str1_5,my_ralph1.display()) << "FAIL: display" ;
}
/*
string except_str1_1 = "Fly with wings at speed of 20 mph.";
ASSERT_STREQ(except_str1_1.c_str(),my_ralph.performFly()) << "FAIL: display" ;
*/
TEST(MallardTest,Constructor){
  Mallard my_ralph2;
  string except_str2_1 = "Fly with wings at speed of 5 mph.";
  EXPECT_EQ(except_str2_1,my_ralph2.performFly()) << "FAIL: performFly" ;

  string except_str2_2 = "Quack at 10 decibels.";
  EXPECT_EQ(except_str2_2,my_ralph2.performQuack()) << "FAIL: performQuack" ;

  Squeak s(2);
  my_ralph2.setQuackBehavior(&s);
  string except_str2_3 = "Quack at 2 decibels.";
  EXPECT_EQ(except_str2_3,my_ralph2.performQuack()) << "FAIL: performQuack of setQuackBehavior" ;

  NoFly n;
  my_ralph2.setFlyBehavior(&n);
  string except_str2_4 = "Cannot fly.";
  EXPECT_EQ(except_str2_4,my_ralph2.performFly()) << "FAIL: performFly of setFlyBehavior" ;
}

TEST(MallardTest,display){
  Mallard my_ralph3;
  string except_str2_5="I am a Mallard.";
  EXPECT_EQ(except_str2_5,my_ralph3.display()) << "FAIL: display" ;
} 
#endif
