/* STUDENTS:  DO NOT EDIT THIS FILE.  INSTEAD, CREATE YOUR OWN UNIT TESTS ACCORDING
TO THE LAB DOCUMENT.
*/

// Google Test Framework
#include <gtest/gtest.h>
// Project code from the ../src directory
#include "../src/QuackBehavior.h"
#include <string.h>

#ifdef FEEDBACK_TEST_03

TEST(QuackBehaviorTest, Constructor) {
  Quack my_quack;
  string expect_str="Quack at 10 decibels.";
  EXPECT_STREQ(expect_str.c_str(),my_quack.quack().c_str())<<"FAIL:Quack Constructor!";
}

TEST(Quack, Constructor) {
  Quack my_quack;
  string expect_str="Quack at 10 decibels.";
  EXPECT_STREQ(expect_str.c_str(),my_quack.quack().c_str())<<"FAIL:Quack Constructor!";
}

TEST(Quack, quack) {
  Quack my_quack;
  string expect_str="Quack at 10 decibels.";
  EXPECT_STREQ(expect_str.c_str(),my_quack.quack().c_str())<<"FAIL:Quack Constructor!";
}

TEST(Squeak, Constructor) {
  Squeak my_quack1;
  Squeak my_quack2(100);
  string expect_str1="Quack at 10 decibels.";
  EXPECT_STREQ(expect_str1.c_str(),my_quack1.quack().c_str())<<"FAIL:Quack Constructor!";
  string expect_str2="Quack at 100 decibels.";
  EXPECT_STREQ(expect_str2.c_str(),my_quack2.quack().c_str())<<"FAIL:Quack Constructor!";
}

TEST(Squeak, quack) {
  Squeak my_quack1_1;
  Squeak my_quack2_2(12);
  string expect_str1_1="Quack at 10 decibels.";
  EXPECT_STREQ(expect_str1_1.c_str(),my_quack1_1.quack().c_str())<<"FAIL:Quack Constructor!";
  string expect_str2_2="Quack at 12 decibels.";
  EXPECT_STREQ(expect_str2_2.c_str(),my_quack2_2.quack().c_str())<<"FAIL:Quack Constructor!";
}

#endif
